name: test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  unit:
    name: unit / ${{matrix.os}} / node v${{matrix.node_version}}
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node_version: [18, 20, 22, 23]
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Use Node ${{matrix.node_version}}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node_version }}
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install dependencies
        run: pnpm install
      - name: Build dependencies
        run: pnpm run build
      - name: Run Tests
        run: pnpm run test
      - name: Run TS Smoke Tests
        run: pnpm run test:ts
      - name: Lint Prettier
        run: pnpm run lint:prettier
      - name: Lint ESLint
        run: pnpm run lint
